server:
  port: ${TODO_SERVICE_PORT}  # Default to 8082 if env var not set

spring:
  application:
    name: todo-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${TODO_JPA_DDL}
    show-sql: ${TODO_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#
#
#  endpoints:
#    web:
#      exposure:
#        include: health,info,prometheus

#otel:
#  service:
#    name: todo-service
#  exporter:
#    otlp:
#      endpoint: http://otel-collector:4318